To Do list: add & remove
EmiLoKiJu/to-do-list pull request #2
Opened 2023-05-04 17:28 UTC by EmiLoKiJu

Functionality to add, remove and edit:
- Double click on the text to edit
- Press enter or click on the enter icon to add an element to the list
- Press the delete button with the thrash icon to delete element

2023-05-04 19:29 UTC, Shisui6 requested changes
Hi @EmiLoKiJu, 

# Requires Changes 🍀
You have done a great job so far!👏👏
Your project is almost complete. There are a few issues that you still need to work on🪲.

## Highlights
- Add function created ✅


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 19:29 UTC, Shisui6 commented on src/modules/iteratearray.js
> +  deletebutton.addEventListener('click', () => {
After following the instructions in your PR description, I am unable to delete a task as seen in the video below:


https://user-images.githubusercontent.com/37116322/236305474-098f3c29-854e-497a-a65d-65aa3bef8df6.mp4



Please update your app to include task deletion functionality as stated in the project requirements🙏

2023-05-04 19:29 UTC, Shisui6 commented on src/modules/iteratearray.js
> +const editelement = (listelement, elementcontainer, arr, i) => {
Currently, editing a task is not saved in local storage as seen in the video below:


https://user-images.githubusercontent.com/37116322/236309553-2b3f54d4-87d9-4a0f-9715-5570ba68adde.mp4



Please update your app so that task edits are saved to local storage as stated in the project requirements

2023-05-04 19:29 UTC, Shisui6 commented on src/index.js
>  inputElement.addEventListener('keyup', (event) => {
[Optional] Please consider clearing the input field whenever a new task is added. This will greatly improve the user experience

2023-05-04 20:14 UTC, TuyishimireEric commented
# INVALID ❌ ❌ ❌
### Hi @EmiLoKiJu   👋

While you made a great effort in this project, I can't go ahead and review your code.

## Invalid Code Review Request ❌
You have submitted a project that is not checking for Linter Errors 😨, Kindly configure Linters and submit again once you are done 🙏  
![image](https://user-images.githubusercontent.com/102757126/236319074-9432adfc-4f64-471d-921e-b112ce5e2b49.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Kindly create  a new PR that follows the Gitflow approach

Cheers, and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

---
_Invalid Code Review Request does not count into the code reviews limit._

2023-05-04 20:54 UTC, Kamba56 requested changes
Hi @EmiLoKiJu, 

Great work on making the changes requested by a previous reviewer 👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] Great job persisting data to the localstorage!👏👏👏
- [x] Great job adding an edit functionality👏👏👏

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 20:54 UTC, Kamba56 commented on src/modules/iteratearray.js
> +    iteratearray(arr);
- [ ] The delete functionality is still not working. Kindly make the delete button remove the item as demanded by the project requirements.

2023-05-05 04:35 UTC, shella12 approved these changes
Hi @EmiLoKiJu, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Implemented all required functions 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 04:37 UTC, merged